version: '3.9'

services:
  django:
    container_name: ticket-django
    image: django-docker:0.0.1
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - '.:/code'
    depends_on:
      - database

  database:
    image: postgres:12.0
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
