# Generated by Django 4.1.7 on 2023-03-11 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('fires_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=25)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('active', models.BooleanField()),
                ('people', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='core.people')),
            ],
        ),
    ]
