# Generated by Django 4.1.7 on 2023-03-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_intheaters_room_seat_session_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='room_id',
        ),
        migrations.AddField(
            model_name='session',
            name='room_id',
            field=models.ManyToManyField(to='core.room'),
        ),
    ]
